---
galaxy_info:
  role_name: s3_website
  author: Your Name
  description: Deploy static websites to AWS S3
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Amazon
      versions:
        - all
  galaxy_tags:
    - aws
    - s3
    - website
    - static

# dependencies:
#   - name: amazon.aws.s3_bucket
#     version: ">=2.0.0"
#   - name: community.aws
#     version: ">=3.0.0"