apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - serviceaccount-crb.yaml
  - pv.yaml
  - pvc.yaml
  - deploy.yaml
  - service.yaml
