apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sa-jenkins.yaml
  - role.yaml
  - rolebinding.yaml
  - secret.yaml
  - configmap.yaml
  - pv.yaml
  - pvc.yaml
  - deploy.yaml
  - service.yaml
