#Admin password for jenkins
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-creds
  namespace: jenkins
type: Opaque
stringData:
  ADMIN_PASSWORD: "admin123"

# Secret token for sa
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-sa-token-secret
  namespace: jenkins
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token
