apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"jenkins"},"name":"jenkins-service","namespace":"jenkins"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":8080},{"name":"jnlp","port":50000,"protocol":"TCP","targetPort":50000}],"selector":{"app":"jenkins"},"type":"LoadBalancer"}}
  creationTimestamp: "2025-10-30T12:40:39Z"
  labels:
    app: jenkins
  name: jenkins-service
  namespace: jenkins
  resourceVersion: "76803"
  uid: 109fc0f1-c114-47b8-aff5-eb86454b62f6
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.212.70
  clusterIPs:
  - 10.98.212.70
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30000
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jnlp
    nodePort: 32237
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: jenkins
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
